// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteKrco8NjAVrnMwpFmlczRvwEKGPPGzM',
    appId: '1:102031324992:web:1a52aea51e716f1c88aca5',
    messagingSenderId: '102031324992',
    projectId: 'moon-d24e8',
    authDomain: 'moon-d24e8.firebaseapp.com',
    storageBucket: 'moon-d24e8.appspot.com',
    measurementId: 'G-BWRFE5479Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEv0b_UNCym7-N2cP9j6q62mgE6lgDsg',
    appId: '1:102031324992:android:edaed3d882b6c0c288aca5',
    messagingSenderId: '102031324992',
    projectId: 'moon-d24e8',
    storageBucket: 'moon-d24e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7jVR_A7cB5bLUdUt49L5XMHTyGTAp0c',
    appId: '1:102031324992:ios:f237694be6c3b43088aca5',
    messagingSenderId: '102031324992',
    projectId: 'moon-d24e8',
    storageBucket: 'moon-d24e8.appspot.com',
    iosClientId: '102031324992-17bf8kiu8d1ea66rfne83ettupfp8j9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY7jVR_A7cB5bLUdUt49L5XMHTyGTAp0c',
    appId: '1:102031324992:ios:f237694be6c3b43088aca5',
    messagingSenderId: '102031324992',
    projectId: 'moon-d24e8',
    storageBucket: 'moon-d24e8.appspot.com',
    iosClientId: '102031324992-17bf8kiu8d1ea66rfne83ettupfp8j9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAteKrco8NjAVrnMwpFmlczRvwEKGPPGzM',
    appId: '1:102031324992:web:dc8cc4091fd6c74688aca5',
    messagingSenderId: '102031324992',
    projectId: 'moon-d24e8',
    authDomain: 'moon-d24e8.firebaseapp.com',
    storageBucket: 'moon-d24e8.appspot.com',
    measurementId: 'G-TKF4LN44RH',
  );
}
